Subvault UI/Controllers/SubtitlesController.cs
using Subvault_Domain;
using Subvault_Domain.Entities;
using Subvault_UI.ActionFilters;
using Subvault_UI.BusinessLogic;
using System.Web;
using System.Web.Mvc;

namespace Subvault_UI.Controllers {

    public class SubtitlesController : Controller {

        private ItemManager ItemManager;
        private SubtitlesManager SubtitlesManager;

        public SubtitlesController(ItemManager itemManager, SubtitlesManager subtitlesManager) {
            ItemManager = itemManager;
            SubtitlesManager = subtitlesManager;
        }

        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Returns the view for uploading subtitles
        /// </summary>
        /// <returns>The view</returns>
        [HttpGet]
        [UserLoggedIn]
        public ViewResult UploadForMovie() {
            Logger.Log.InfoFormat(Logger.Format + "GET Request for UploadForMovie", GetType().ToString());
            ViewBag.Type = "Movie";
            return View("Upload");
        }

        [HttpGet]
        [UserLoggedIn]
        public ViewResult UploadForSeries() {
            Logger.Log.InfoFormat(Logger.Format + "GET Request for UploadForSeries", GetType().ToString());
            ViewBag.Type = "Series";
            return View("Upload");
        }


        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Catches the request to upload subtitles
        /// </summary>
        /// <param name="subtitles">Subtitles data</param>
        /// <param name="itemId">The id of the movie the subtitles belong to</param>
        /// <param name="file">The subtitles file</param>
        /// <returns>Redirects to the homepage</returns>
        [HttpPost]
        [UserLoggedIn]
        public ActionResult UploadForMovie(Subtitles subtitles, int itemId, HttpPostedFileBase file) {
            Logger.Log.InfoFormat(Logger.Format + "POST Request for UploadForMovie for movie with id: " + itemId + " and subtitles: " + subtitles.ToString(), GetType().ToString());
            SubtitlesManager.UploadForMovie(subtitles, itemId, file);
            TempData["upload-success"] = true;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [UserLoggedIn]
        public ActionResult UploadForSeries(Subtitles subtitles, int itemId, int episodeId, HttpPostedFileBase file) {
            Logger.Log.InfoFormat(Logger.Format + "POST Request for UploadForSeries for series with id: " + itemId + " and episode with id: " + episodeId + " and subtitles: " + subtitles.ToString(), GetType().ToString());
            SubtitlesManager.UploadForSeries(subtitles, itemId, episodeId, file);
            TempData["upload-success"] = true;
            return RedirectToAction("Index", "Home");
        }

        public FileResult Download(string filePath, string fileName) {
            Logger.Log.InfoFormat(Logger.Format + "Download request for fileName: " + fileName + " and filePath: " + filePath, GetType().ToString());
            string contentType = "text/plain";
            return File(filePath, contentType, fileName);
        }
    }
}

Subvault UI/Controllers/UserController.cs
using Subvault_Domain;
using Subvault_Domain.Exceptions;
using Subvault_UI.BusinessLogic;
using Subvault_UI.Models;
using System.Web.Mvc;

namespace Subvault_UI.Controllers {

    public class UserController : Controller {

        private UserManager userManager;

        public UserController(UserManager userManager) {
            this.userManager = userManager;
        }

        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Catches the login request and redirects back to the page the request came from
        /// </summary>
        /// <param name="login">Model containing the username and password</param>
        public void Login(LoginViewModel login) {
            Logger.Log.InfoFormat(Logger.Format + "Login request for user: " + login.Username, GetType().ToString());

            TempData["Login"] = login;

            try {
                //If the password is correct
                if (!userManager.AuthenticateUser(login.Username, login.Password)) {
                    Logger.Log.InfoFormat(Logger.Format + "Login request for user: " + login.Username + " failed, because username or password was incorrect", GetType().ToString());
                    TempData["UsernameOrPasswordIncorrect"] = true;
                } else {
                    //Set login session
                    Logger.Log.InfoFormat(Logger.Format + "Login request for user: " + login.Username + " was successful", GetType().ToString());
                    Session["Login"] = userManager.GetUserSession(login.Username);
                }
            } catch (UserDoesNotExistException udnee) {
                Logger.Log.InfoFormat(Logger.Format + "Login request for user: " + login.Username + " failed, because a user with that username does not exist", GetType().ToString());
                TempData["UserDoesNotExist"] = udnee.Message;
            }

            Response.Redirect(Request.UrlReferrer.ToString());
        }

        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Logs out the user and redirects the user to the homepage
        /// </summary>
        public void Logout() {
            Logger.Log.InfoFormat(Logger.Format + "Logout request for user: " + ((UserSessionViewModel)Session["Login"]).Username, GetType().ToString());

            //Set login session to null
            Session["Login"] = null;

            //Return to home
            Response.Redirect("/");
        }

        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Returns the view to register a user
        /// </summary>
        /// <returns>The view</returns>
        [HttpGet]
        public ViewResult Register() {
            Logger.Log.InfoFormat(Logger.Format + "GET request for Register", GetType().ToString());
            return View();
        }

        /// <author>Dennis van Hest</author>
        /// <summary>
        /// Catches the user register request
        /// </summary>
        /// <param name="registeringUser">The user to be registered</param>
        /// <returns>The ThanksForRegistering view if everything is correct. Otherwise it will return to the register page.</returns>
        [HttpPost]
        public ViewResult Register(RegisteringUser registeringUser) {
            Logger.Log.InfoFormat(Logger.Format + "POST request for Register for user: " + registeringUser.ToString(), GetType().ToString());

            if (ModelState.IsValid) {
                try {
                    userManager.RegisterUser(registeringUser);
                } catch (UserAlreadyExistsException uaee) {
                    Logger.Log.InfoFormat(Logger.Format + "POST request for Register for user: " + registeringUser.ToString() + " failed, because the user with that username already exists", GetType().ToString());
                    ViewBag.UserAlreadyExists = uaee.Message;
                    return View();
                } catch (PasswordNotEqualToPasswordRepeatException pnetpre) {
                    Logger.Log.InfoFormat(Logger.Format + "POST request for Register for user: " + registeringUser.ToString() + " failed, because the password did not match the password repeat", GetType().ToString());
                    ViewBag.PasswordRepeatNotTheSame = pnetpre.Message;
                    return View();
                }

                Logger.Log.InfoFormat(Logger.Format + "POST request for Register for user: " + registeringUser.ToString() + " was successful", GetType().ToString());

                return View("ThanksForRegistering");
            } else {
                return View();
            }
        }
    }
}

Subvault UI/Views/Shared/_ItemBox.cshtml
@using Subvault_Domain

@model Subvault_Domain.Entities.Item

<div class="item-box">
    <div class="image-box">
        @if (!String.IsNullOrEmpty(Model.PosterPath)) {
            <img src="@GlobalSettings.APIImageRoot/w@(GlobalSettings.ItemBoxPosterWidth)@(Model.PosterPath)" />
        } else {
            <img src="~/Content/img/img-not-available.png" />
        }
    </div>
    <div class="item-info-box">
        <h3 title="@Model.Title">@Model.Title</h3>
        @if (Model is Subvault_Domain.Entities.Movie) {
            <a href="@Html.Raw("/Movie/" + Model.Id)"><button class="green-button">Subtitles <i class="fa fa-arrow-right" aria-hidden="true"></i></button></a>
        } else {
            <a href="@Html.Raw("/Series/" + Model.Id)"><button class="green-button">Subtitles <i class="fa fa-arrow-right" aria-hidden="true"></i></button></a>
        }
    </div>
</div>

Subvault UI/Views/Shared/_ItemCard.cshtml
@using Subvault_Domain

@model Subvault_Domain.Entities.Item

<div class="item-card">
    <div class="poster">
        <img src="@GlobalSettings.APIImageRoot/w@(GlobalSettings.ItemCardPosterWidth)@(Model.PosterURL)" />
    </div>
    <div class="info">
        <h2>@Model.Title</h2>
        <div class="subtitle-icon"><i class="fa fa-cc" aria-hidden="true"></i></div><div class="available-languages"><p>English, Dutch, Spanish, French...</p></div>
        @if (Model is Subvault_Domain.Entities.Movie) {
            <a href="@Html.Raw("/Movie/" + Model.Id)"><button class="green-button">Subtitles <i class="fa fa-arrow-right" aria-hidden="true"></i></button></a>
        } else {
            <button class="green-button">Subtitles <i class="fa fa-arrow-right" aria-hidden="true"></i></button>
        }
    </div>
</div>

Subvault UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Subvault</title>

    <!-- Bootstrap CSS -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Custom CSS -->
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway:400,900" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="~/Content/font-awesome.css" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script src="~/Scripts/mobile-nav.js"></script>

    <script src="~/Scripts/multiselect.js"></script>

    <script src="~/Scripts/upload-dialog.js"></script>

    @RenderSection("Scripts", false)
</head>
<body>
    <div class="dialog" id="upload-dialog">
        <div class="dialog-inner">
            <p>For what would you like to upload subtitles?</p>
            <button class="dialog-close">X</button>
            <div class="col-xs-6"><a href="/Movie/Subtitles/Upload"><button>For a movie</button></a></div>
            <div class="col-xs-6"><a href="/Series/Subtitles/Upload"><button>For a series</button></a></div>
        </div>
    </div>

    <nav id="mobile-nav" class="hidden-sm hidden-md hidden-lg hidden-xl">
        <button><i class="fa fa-bars" aria-hidden="true"></i></button>
        <a href="/">
            <div id="logo-area">
                <h1><span>Sub</span>vault</h1>
            </div>
        </a>
    </nav>
    <nav id="side-nav">
        <a href="/" class="hidden-xs">
            <div id="logo-area">
                <h1><span>Sub</span>vault</h1>
            </div>
        </a>

        @Html.Partial("_NavSearch", new Subvault_UI.Models.SearchQuery())

        <div class="multiselect">
            <button>All languages<i class="fa fa-chevron-down" aria-hidden="true"></i></button>
            <div class="multi-dropdown">
                <ul>
                    @foreach (KeyValuePair<string, string> language in Subvault_Domain.GlobalSettings.LanguageCodes) {
                        <li>
                            <input id="multiselect-@language.Key" type="checkbox" name="language-multiselect" value="@language.Key" />
                            <label class="sub-spec-label" for="multiselect-@language.Key"><span></span> @language.Value</label>
                        </li>
                    }
                </ul>
            </div>
        </div>

        @if (Session["Login"] == null) {
            if (TempData["Login"] != null) {
                @Html.Partial("_NavLogin", TempData["Login"]);
            } else {
                @Html.Partial("_NavLogin", new Subvault_UI.Models.LoginViewModel());
            }
        } else {
            @Html.Partial("_NavUser", Session["Login"])
        }
    </nav>

    <div id="content">
        @RenderBody()
    </div>
</body>
</html>

Subvault UI/Views/Shared/_MovieSubtitlesList.cshtml
@using Subvault_Domain
@using System.Web.UI.WebControls
@using System.Web.Mvc

@model IEnumerable<Subvault_Domain.Entities.Subtitles>

@{
    var listItems = new List<ListItem>();
    listItems.Add(new ListItem { Text = "All languages", Value = "all", Selected = true });
    foreach (KeyValuePair<string, string> language in Subvault_Domain.GlobalSettings.LanguageCodes) {
        listItems.Add(new ListItem { Text = language.Value, Value = language.Key });
    }
}

<div id="subtitles-list" class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <div class="col-xs-12"><h4>Subtitles</h4></div>
    <div id="subtitles-table">
        @Html.DropDownList("language-select", new SelectList(listItems, "Value", "Text"))
        <table>
            <thead>
                <tr>
                    <td class="sort hidden" data-sort="language"></td>
                    <td class="sort" data-sort="language-icon"><div class="tooltip"><i class="fa fa-flag" aria-hidden="true"></i><span class="tooltiptext">Language</span></div></td>
                    <td class="sort" data-sort="file-name">Name</td>
                    <td class="sort" data-sort="synced-with">Synced with</td>
                    <td class="sort" data-sort="hearing-impaired"><div class="tooltip"><i class="fa fa-deaf" aria-hidden="true"></i><span class="tooltiptext">For hearing impaired</span></div></td>
                    <td class="sort" data-sort="foreign-only"><div class="tooltip"><i class="fa fa-globe" aria-hidden="true"></i><span class="tooltiptext">Foreign speech only</span></div></td>
                    <td class="sort" data-sort="uploader">Uploader</td>
                    <td class="sort" data-sort="download-button"></td>
                </tr>
            </thead>
            <tbody class="list">
                @if (Model != null && Model.Count() != 0) {
                    foreach (Subvault_Domain.Entities.Subtitles subtitles in Model) {
                        <tr>
                            <td class="language hidden">@subtitles.Language</td>
                            <td class="language-icon" value="@subtitles.Language"><img src="~/Content/flags/4x3/@(subtitles.Language).svg" title="@GlobalSettings.LanguageCodes[subtitles.Language]" /></td>
                            <td class="file-name">@subtitles.FileName</td>
                            <td class="synced-with">@subtitles.SyncType</td>
                            <td class="hearing-impaired">@if (subtitles.ForHearingImpaired) { <i class="fa fa-check" aria-hidden="true"></i> }</td>
                            <td class="foreign-only">@if (subtitles.IsForeignOnly) { <i class="fa fa-check" aria-hidden="true"></i> }</td>
                            <td class="uploader">@subtitles.Uploader.Username</td>
                            <td class="download-button"><a href="@Url.Action("Download", "Subtitles", new { filePath = subtitles.FilePath, fileName = subtitles.FileName })"><button type="submit" class="green-button"><i class="fa fa-download" aria-hidden="true"></i></button></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @if (Model == null || Model.Count() == 0) {
            <p class="no-subs">No subtitles available for this movie... Yet...</p>
        }
    </div>
</div>

Subvault UI/Views/Shared/_NavLogin.cshtml
@model Subvault_UI.Models.LoginViewModel

<div id="nav-login-register">
    <div id="nav-login">
        <h4><i class="fa fa-user" aria-hidden="true"></i>  Login or Register</h4>
        @using (Html.BeginForm("Login", "User")) {

            if (TempData["UsernameOrPasswordIncorrect"] != null) {
                <div class="input-error-message"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>  Either the username or password was incorrect.</div>
            }

            @Html.TextBoxFor(u => u.Username, new { @placeholder = "Username" })
            if (TempData["UserDoesNotExist"] != null) {
                <div class="input-error-message"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>  @TempData["UserDoesNotExist"]</div>
            }
            @Html.TextBoxFor(u => u.Password, new { @placeholder = "Password", @type = "password" })
            <button type="submit" class="green-button">Login</button>
        }
    </div>
    <div id="nav-register">
        <p>Don't have an account?</p>
        <a href="@Url.Action("Register", "User")"><button class="green-button, transparent-button">Register</button></a>
    </div>
</div>

Subvault UI/Views/Shared/_NavSearch.cshtml
@model Subvault_UI.Models.SearchQuery

<div id="search-area">
    @using (Html.BeginForm("Search", "Search", FormMethod.Get)) {
        @Html.TextBoxFor(searchQuery => searchQuery.Title, new { placeholder = "Search..." })
        <button type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    }
</div>

Subvault UI/Views/Shared/_NavUser.cshtml
@model Subvault_UI.Models.UserSessionViewModel

<div id="nav-user">
    <h3><i class="fa fa-user" aria-hidden="true"></i>  @Model.Username</h3>
    <button class="green-button" id="upload-button"><i class="fa fa-upload" aria-hidden="true"></i>   Upload</button>
    <a href="@Url.Action("Logout", "User")"><button class="green-button transparent-button" id="logout-button">Logout</button></a>
</div>

Subvault UI/Views/Shared/_SeasonEpisodesList.cshtml
@model IEnumerable<Subvault_Domain.Entities.Episode>

<div id="seasons-list" class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h4>Episodes</h4>
    <table>
        <thead>
            <tr>
                <td>#</td>
                <td>Name</td>
                <td>Air date</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (Subvault_Domain.Entities.Episode episode in Model) {
                <tr>
                    <td>@episode.EpisodeNumber</td>
                    <td>@episode.Name</td>
                    @if (episode.AirDate != null) {
                        <td>@episode.AirDate.Value.ToString("MM-dd-yyyy")</td>
                    } else {
                        <td>No air date</td>
                    }
                    <td><a href="/Series/@(episode.Season.Series.Id)/Season/@(episode.Season.SeasonNumber)/Episode/@(episode.EpisodeNumber)"><button class="green-button"><i class="fa fa-chevron-right" aria-hidden="true"></i></button></a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

Subvault UI/Views/Shared/_SeriesSeasonsList.cshtml
@model IEnumerable<Subvault_Domain.Entities.Season>

<div id="seasons-list" class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h4>Seasons</h4>
    <table>
        <thead>
            <tr>
                <td>#</td>
                <td>Name</td>
                <td>Air date</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (Subvault_Domain.Entities.Season season in Model) {
                <tr>
                    <td>@season.SeasonNumber</td>
                    <td>@season.Name</td>
                    @if (season.AirDate != null) {
                        <td>@season.AirDate.Value.ToString("MM-dd-yyyy")</td>
                    } else {
                        <td>No air date</td>
                    }
                    <td><a href="/Series/@(season.Series.Id)/Season/@(season.SeasonNumber)"><button class="green-button"><i class="fa fa-chevron-right" aria-hidden="true"></i></button></a></td>
                </tr>
            }
        </tbody>
    </table>
</div>